project:
  type: website
  resources: 
    - "*.pdf"
    - "*.doc"
    - "obyLecture.html"

website:
  title: "Lecture Repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tnbcSubclassification.qmd
        text: TNBC Subclassification
      - href: p16Genomics.qmd
        text: p16 Genomics
      - href: Neoadjuvant.qmd
        text: Neoadjuvant
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

